redis:
  image: redis
  ports:
    - "6379:6379"

rabbitmq:
  image: rabbitmq:3.5.3-management
  ports:
    - "5672:5672"
    - "15672:15672"
   
mongodb:
  image: mongo:3.0.4
  ports:
    - "27017:27017"
  command: mongod --smallfiles
    
toolbox-discovery-service:
  build: ./toolbox/discovery-service
  ports:
    - "8761:8761"
     
backend-catalog-service:
  build: ./backend-services/catalog-service
  ports:
    - "9000:8080"