spring:
  application:
    name: discovery-service
  cloud:
    ignoredInterfaces:
      - lo*
  config:
      uri: http://localhost:8004

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8001/eureka