debug: true
server.port: 8081
spring.application.name: checkout-service

spring:
  cloud:
      ignoredInterfaces:
        - lo*
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/