spring.application.name: checkout-service

spring:
  cloud:
      ignoredInterfaces:
        - lo*
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/