spring.application.name: checkout-service

#logging:
#  level:
#    com.netflix.discovery: 'DEBUG'
#    org.springframework.cloud: 'DEBUG'
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/