orderfy:
  orders:
    queue-name: orderfy-orders-queue
    exchange-name: orderfy-orders-exchange

spring:
  application:
    name: orders-service
  cloud:
    ignoredInterfaces:
      - lo*

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka