spring.application.name: discovery-service

eureka:
  instance:
    hostname: orderfy
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/