spring:
  application:
    name: apigateway-service
  cloud:
    stream:
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbitmq

eureka:
  client:
    serviceUrl:
      defaultZone: http://ds-toolbox-discovery-service:8080/eureka/
