spring:
  application:
    name: instancesadmin-service
  cloud:
    ignoredInterfaces:
      - lo*
  config:
      uri: http://localhost:8004

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka