spring.application.name: search-service

spring:
  cloud:
      ignoredInterfaces:
        - lo*
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/